#! /usr/bin/env bash
set -e # exit entire script when command exits with non-zero status

npm install

# @TODO: Write script to bump version numbers

expo publish --release-channel production --non-interactive

# Start building standalone android build using `production` release channel
expo build:android --release-channel production --non-interactive --no-publish

# Download the built android binary
curl -o app.apk "$(expo url:apk --non-interactive)"

# Use fastlane to upload your current standalone android build
# Customize this to fit your needs. Take note of env variables.
# Check out https://docs.fastlane.tools for more info.
fastlane supply --track 'alpha' --json_key '/Users/daybreaker/Downloads/api-5703996670531471288-735731-365ec0cf004c.json' --package_name "com.revelrylabs.bigneon" --apk "app.apk" --skip_upload_metadata --skip_upload_images --skip_upload_screenshots


# Start building standalone ios build using `production` release channel
expo build:ios --release-channel production --non-interactive --no-publish

# Download the artifact to current directory as `app.ipa`
curl -o app.ipa "$(expo url:ipa --non-interactive)"

# Use fastlane to upload your current standalone iOS build to test flight on iTunes Connect.

fastlane deliver --verbose --ipa "app.ipa" --skip_screenshots --skip_metadata
# fastlane pilot upload --verbose --ipa "app.ipa"


